### ISSUE TITLE
Crashes when encountering files that aren't images

### ISSUE THREAD

**Issue by dokutan** [danbooru/autotagger#2]
When running ``autotag`` on a non-image file or a directory containing files other than images, ``autotag`` crashes with this error (e.g ``./autotag autotag``):
```
Traceback (most recent call last):
  File "…/autotagger/./autotag", line 64, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "…/autotagger/./autotag", line 36, in main
    for filepath, tags in zip(filepaths, predictions):
  File "…/autotagger/autotagger.py", line 31, in predict
    images = [PILImage.create(file) for file in files]
  File "…/autotagger/autotagger/autotagger.py", line 31, in <listcomp>
    images = [PILImage.create(file) for file in files]
  File "…/.local/lib/python3.10/site-packages/fastai/vision/core.py", line 120, in create
    return cls(load_image(fn, **merge(cls._open_args, kwargs)))
  File "…/.local/lib/python3.10/site-packages/fastai/vision/core.py", line 95, in load_image
    im = Image.open(fn)
  File "/usr/lib/python3.10/site-packages/PIL/Image.py", line 3123, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='autotag'>
```

**Comment by dokutan** [comment]
I just noticed that the wrong filenames are used when files are skipped. eg ``./autotag not-an-image image.jpg`` results in:
```
not-an-image,…
```
